### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by unuseless** [justanr/flask-allows#12]
Enhancement ideas for the documentation:

- The readme states: `allows = Allows(identity_loader=lambda: g.user)`, whereas the documentation string for `Allows(object)` states: `allows = Allows(app=app, identity_loader=lambda: current_user)`. Why needs app to be passed in in the second call, and not in the first?
- When/where do we need to do the above call? e.g. in each source file allows is used, once for every blueprint, or ...?
- If Flask-Login is uses, and the identity_loader is current_user `allows = Allows(identity_loader=lambda: current_user)`, I get an error: ```
flask_allows/allows.py", line 130, in fulfill
  identity = identity or self._identity_loader()
  TypeError: 'NoneType' object is not callable
``` when calling like this: `if Permission(is_staff):`
and no error when calling like this: `if Permission(is_staff, identity=current_user):`

**Comment by justanr** [comment]
Flask-Allows follows the convention of providing an `init_app` for delayed application initialization.  If the app is provided in the Allows constructor, it calls init app for you, otherwise you must call it later.

Both of these calls need to be made only once. I prefer application factories (e. g. there's a function that creates the actual application instance for me), so I end up calling both. This is also the way that sh4nks/flaskbb sets up Allows. The Allows instance is created in the extensions module and then init app is called when the application is created. I'd recommend taking a peek at that project for a concrete example. 

Let me know if have any other questions.

**Comment by justanr** [comment]
Didn't see the third question. Flask-Login only populates the current user object when a request is loaded and you've told it how to load the user. I'd have to see a fuller code example to help you with that issue. But if it's working as you say, then that is definitely strange behavior.

**Comment by unuseless** [comment]
In `__init__.py` flask-allows is loaded and initialized.

Then in example.py:

```
# flask allows testing
from flask_login import login_required, current_user, login_user
from flask_allows import Allows, Permission
allows = Allows(identity_loader=lambda: current_user)

def is_staff(ident, request):
    # return ident.permlevel == 'staff'
    print ident
    print request
    # just for test:
    return True

@main.route('/', methods=['GET'])
# @allows.requires(is_staff)
def index():
    print current_user
    if Permission(is_staff, identity=current_user):
       return "hi"
    else:
       return "sorry"
```
the above works if I explicitly pass in the identity as shown.  If I just use Permission(is_staff), I get the TypeError.

**Comment by unuseless** [comment]
It seems the issue was because of loading flask-allows twice.

It was loaded in `__init__.py`, and then again in the example file.
`allows = Allows(identity_loader=lambda: current_user)`
instead you should use:
`allows.identity_loader(lambda: current_user)`
So my struggle had to do with initializing flask-allows.
Can you add to the documentation something like:

`allows = Allows()`
and in an application factory:
``allows.init_app(app)`

Then in you views you can define the user loader:
`allows.identity_loader(lambda: current_user)`

**Comment by justanr** [comment]
Flask-Allows initialization is pretty common for Flask extensions. There's also no fundamental difference between `Allows(identity_loader=...)` and `allows.identity_loader(...)` other than when the callback is registered.

I'm happy to provide some more documentation if needed though.

**Comment by justanr** [comment]
@unuseless I'm currently writing more in depth documentation. You can follow the progress at #15

**Comment by unuseless** [comment]
Idea for enhancement:
When using Flask-Login, a decorator called `@login_required` can be used.  If this is used together with the flask-allows decorator, should it be like this:

```@allows.requires(IsAdmin())
@login_required``

or

``@login_required
@allows.requires(IsAdmin())``

So advice on the order of the decorators would be helpful.

**Comment by justanr** [comment]
@unuseless take a look at the RTD link in the associated pull request and let me know what you think.

**Comment by unuseless** [comment]
@justanr Thank you, the docs are a great improvement.
Comments:

- Would be great if you add an example together with flask-login like in my question from  a couple of days ago in this thread.
- In https://flask-allows.readthedocs.io/en/documentation/quickstart.html you give a warning that "The requires() decorator must be applied before the route registration otherwise the unguarded route will be registered into the routing table." This is unclear to a beginner (when is first, logically or in line numbers).  Would suggest to remove this.  In https://flask-allows.readthedocs.io/en/documentation/helpers.html you give a much more helpful and thorough explanation (this is really good).
