### ISSUE TITLE
Thought: Permission entire blueprint

### ISSUE THREAD

**Issue by justanr** [justanr/flask-allows#30]
Rough sketch:

```python
class Allows:
    def run(self, requirements, identity=None, throws=None, on_fail=None):
        identity = identity or self._identity_loader())
        throws = throws or self.throws
        on_fail = _make_callable(on_fail) if on_fail is not None else self.on_fail

        if not self.fulfill(requirements, identity):
            result = on_fail()
            if result is not None:
                return result
            raise throws

    def guard_blueprint(self, bp, requirements, identity=None, throws=None, on_fail=None):
        bp.before_request(lambda: self.run(requirements, identity, throws, on_fail))
```

I feel like I'm potentially missing something here though.

**Comment by susodapop** [comment]
I've been wondering how to do this! We're using `Flask-Allows` for a business intelligence system at my company. Our workaround has been class-based-views: one class for all the views in the blueprints that require executive permissions to monitor. But this would be nicer.

**Comment by justanr** [comment]
If you want to take this for a run as a sort of preview -- just subclass Allows and add the methods above -- and report back on how it preforms, what issues you have, etc that would be fantastic. This hit me as I was riding home on the train today as a sort of "why didn't I do that before."

**Comment by susodapop** [comment]
Will give this a trial run this week on our dev environment and get back to you.

**Comment by justanr** [comment]
Thought: Need to add an escape hatch to unguard some routes. That's why I never did this before.

**Comment by justanr** [comment]
Thought: consider potential of #34 when implementing this. Should expose the requirements onto the blueprint as well for later retrieval.
