### ISSUE TITLE
Set on_fail as global rule

### ISSUE THREAD

**Issue by ar-anvd** [justanr/flask-allows#33]
I don't know if I am missing something here, but using this code in the root  ```__init__.py``` will not override the default werkzeug’s Forbidden exception. I mean like a global rule for the whole application. 

Set the on_fail in all decorators / helpers seems not good here since I am looking for a global exception.

```
from flask_allows import Allows

def redirect_to_home(*args, **kwargs):
    flash("I'm sorry Dave, I'm afraid I can't do that", "error")
    return redirect(url_for("private.index"))

allows = Allows(on_fail=redirect_to_home, identity_loader=lambda: current_user)
```

**Comment by justanr** [comment]
Alright, I'll give this a run through and check for regressions when I get home tonight.

**Comment by ar-anvd** [comment]
@justanr I found the reason. I am using an Application Factory and I am setting the allows initializer only after that, when should be in create_app function (allows.init_app(app)). 

Thanks, and sorry for bother you.

**Comment by justanr** [comment]
No worries.  Glad you figured it out.
